name: save-secret
description: Takes secret value and saves it in the repository secrets.
branding:
  icon: git-commit
  color: green
inputs:
  github_token:
    description: GitHub token used for creating/updating secret. Must have write admin rights.
    required: true
    default: ${{ github.token }}
  repository:
    description: Repository name with owner e.g "octocat/hello-world".
    required: true
    default: ${{ github.repository }}
  secret_name:
    description: Name of the secret to be kept in the repository secrets.
    required: true
  secret_value:
    description: Value to be saved as a secret.
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'